FROM nvidia/cuda:11.2.2-cudnn8-devel-ubuntu20.04

ENV DEBIAN_FRONTEND=noninteractive

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    ffmpeg \
    python3-pip \
    python3-venv

# Set the working directory
WORKDIR /server

# Copy requirements file and install Python dependencies
COPY requirements.txt /server/requirements.txt
RUN python3 -m venv venv
RUN . venv/bin/activate && venv/bin/pip install -r requirements.txt

# Copy the rest of the application code
COPY httpServer.py /server/httpServer.py
COPY retriever.py /server/retriever.py
COPY transcribe.py /server/transcribe.py
COPY templates /server/templates
RUN chmod +x /server/httpServer.py /server/retriever.py /server/transcribe.py

# Expose the application port
EXPOSE 5000

# Copy the startup script
COPY start_services.sh /server/start_services.sh
ENTRYPOINT [ "/bin/bash", "/server/start_services.sh" ]